name: Lint files on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Set Github user email
        run: git config --global user.email "manuelsuarezabascal@gmail.com"
      - name: Set Github user name
        run: git config --global user.email "Manuel Abascal"
      - name: Add fix for commit
        run: git add .
      - name: Commit fix
        run: git commit -m "fixed ESLint issues"
      - name: Push fix to current PR branch
        run: git push
