name: Lint files on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node_modules...
        run: npm ci

      - name: Running ESLint & Prettier
        run: npm run format

      - name: Running Cypress E2E test
        run: npm run cypress:all
