name: Lint files & Cypress tests on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node_modules...
        run: npm ci

      - name: Running ESLint check...
        run: npm run lint:check

      - name: Running all Cypress test suites...
        run: npm run cypress run --record --key 49e0281d-7165-4de8-8c1f-c3b6b61dce0e
