name: Lint files & run Cypress test suites on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node_modules...
        run: npm ci

      - name: Running ESLint check...
        run: npm run lint:check

      - name: Launching app in development environment...
        run: npm run serve

      - name: Running all Cypress test suites...
        run: npm run cypress:all
